language: ruby
rvm:
  - "2.0.0"
  - "2.1.1"
  - "2.2.4"
  - "2.3.0"
  - "ruby-head"
  - "rbx-2"
  - "jruby-head"
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
before_install: gem install bundler
